# Generated by Django 6.0.3 on 2026-03-13 02:35

import django.db.models.deletion
import secrets
import utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, choices=[('tv', 'TV'), ('medicine', 'Medicine'), ('reaching', 'Reaching'), ('unknown', 'Unknown')], default='unknown', max_length=20, null=True)),
                ('device_state', models.JSONField(default=dict)),
                ('keypoints', models.JSONField(default=dict)),
                ('inference_result', models.JSONField(blank=True, default=list)),
                ('pose_classification', models.CharField(blank=True, choices=[('lying', 'Lying'), ('reaching', 'Reaching'), ('sitting', 'Sitting'), ('standing', 'Standing'), ('unknown', 'Unknown')], default='unknown', max_length=20, null=True)),
                ('is_keypoints_normalized', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_alert', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_edge_event',
            },
        ),
        migrations.CreateModel(
            name='EdgeDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pir_sensor', 'PIR Sensor'), ('smart_plug', 'Smart Plug'), ('smart_hub', 'Smart Hub')], default='pir_sensor', max_length=20)),
                ('battery_level', models.IntegerField(blank=True, default=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('office', 'Office'), ('garage', 'Garage')], default='living_room', max_length=20)),
                ('special_use', models.CharField(blank=True, choices=[('medicine_cabinet', 'Medicine Cabinet')], max_length=20, null=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('api_key', utils.fields.EncryptedCharField(default=secrets.token_urlsafe, max_length=500, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_provisioned', models.BooleanField(default=False)),
                ('hub_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.edgedevice')),
            ],
            options={
                'db_table': 'api_edge_device',
            },
        ),
    ]
