# Generated by Django 6.0.2 on 2026-03-24 03:36

import django.db.models.deletion
import secrets
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgedevice',
            name='type',
        ),
        migrations.AddField(
            model_name='edgedevice',
            name='device_type',
            field=models.CharField(blank=True, choices=[('pir_sensor', 'PIR Sensor'), ('smart_plug', 'Smart Plug'), ('smart_hub', 'Smart Hub')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='edgeevent',
            name='alert_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edgeevent',
            name='trigger_device',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edgedevice',
            name='api_key',
            field=utils.fields.EncryptedCharField(blank=True, default=secrets.token_urlsafe, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='edgedevice',
            name='location',
            field=models.CharField(blank=True, choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('office', 'Office'), ('garage', 'Garage')], default='living_room', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='edgeevent',
            name='hub_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.edgedevice'),
        ),
    ]
