# Generated by Django 6.0.3 on 2026-03-13 02:57

import secrets
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgedevice',
            name='api_key',
            field=utils.fields.EncryptedCharField(blank=True, default=secrets.token_urlsafe, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='edgedevice',
            name='location',
            field=models.CharField(blank=True, choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('office', 'Office'), ('garage', 'Garage')], default='living_room', max_length=20, null=True),
        ),
    ]
