# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_edgedevice_api_key_alter_edgedevice_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeevent',
            name='trigger_device',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
