# Generated by Django 6.0.3 on 2026-03-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_edgeevent_trigger_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeevent',
            name='alert_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edgeevent',
            name='hub_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.edgedevice'),
        ),
    ]
