# Generated by Django 6.0.2 on 2026-03-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_edgeevent_alert_reasoning_alter_edgeevent_hub_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgedevice',
            name='type',
        ),
        migrations.AddField(
            model_name='edgedevice',
            name='device_type',
            field=models.CharField(blank=True, choices=[('pir_sensor', 'PIR Sensor'), ('smart_plug', 'Smart Plug'), ('smart_hub', 'Smart Hub')], max_length=20, null=True),
        ),
    ]
